name: aoc2023

on:
  push:
    paths:
      - aoc2023/**

jobs:
  aoc2023:
    runs-on: ubuntu-latest
    container: node:21
    defaults:
      run:
        working-directory: aoc2023
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: npm install -g purescript@0.15.13 spago@0.21.0 esbuild@0.19.8
      - run: make publish

      - uses: actions/upload-artifact@v2
        with:
          name: public
          if-no-files-found: error
          path: ./aoc2023/public/**

      - uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./aoc2023/public
          publish_branch: pages
          keep_files: true
